CXX = g++
CXXFLAGS = -g -Wall -o

telephoneMania: telephoneMania.cpp
	$(CXX) $(CXXFLAGS) $@ $<

hashTable: hashTable.cpp
	$(CXX) $(CXXFLAGS) $@ $<

qqLogin: qqLogin.cpp
	$(CXX) $(CXXFLAGS) $@ $<

reverseHashing: reverseHashing.cpp
	$(CXX) $(CXXFLAGS) $@ $<

reverseHashing1: reverseHashing1.cpp
	$(CXX) $(CXXFLAGS) $@ $<

kmp: kmp.cpp
	$(CXX) $(CXXFLAGS) $@ $<
