CPP = g++
CXXFLAGS = -g -Wall -o

sameTree: sameTree.cpp
	$(CPP) $(CXXFLAGS) $@ $<
myAvl: myAvl.cpp
	$(CPP) $(CXXFLAGS) $@ $<
sortTest: sortTest.cpp
	$(CPP) $(CXXFLAGS) $@ $<
myCBP: myCBP.cpp
	$(CPP) $(CXXFLAGS) $@ $<