CXX = g++
CXXFLAGS = -g -Wall -o

heapPath: heapPath.cpp
	$(CXX) $(CXXFLAGS) $@ $<
huffcode: huffcode.cpp
	$(CXX) $(CXXFLAGS) $@ $<
smartPtr: smartPtr.cpp
	$(CXX) $(CXXFLAGS) $@ $<
connectedSet: connectedSet.cpp
	$(CXX) $(CXXFLAGS) $@ $<
